### ISSUE TITLE
Upgrading Django

### ISSUE THREAD

**Issue by jpmckinney** [opennorth/represent-canada#106]
* Django 1.9
  * Drops support for [PostGIS 1.5](https://docs.djangoproject.com/en/1.10/releases/1.9/#miscellaneous), [PostgreSQL 9.0](https://docs.djangoproject.com/en/1.10/releases/1.9/#dropped-support-for-postgresql-9-0)
* Django 1.10
  * Drops support for [PostgreSQL 9.1](https://docs.djangoproject.com/en/1.10/releases/1.10/#dropped-support-for-postgresql-9-1)

PostgreSQL >= 9.4 would allow us to drop [jsonfield](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#jsonfield)

Also, grep for `Django.* \d\.` across all projects when upgrading Django for notes on things to update.

**Comment by rhymeswithcycle** [comment]
Pull request #107 does this upgrade.

I've updated READMEs in `represent-canada` but have not done so or grepped in other projects.

Re dropping jsonfield, note that the builtin Django `JSONField` uses Postgres' native JSON datatype, which would involve a data migration and is probably not necessary (while database-level integrity checking is always nice, we don't otherwise care where Postgres can interpret the JSON data or just treats it as a blob of text).

**Comment by jpmckinney** [comment]
I thought that might be the case. We'll keep jsonfield then.

I've gone through all other repos.
